AWSTemplateFormatVersion: "2010-09-09"
Description: Serverless deployment pipeline for Terraform projects
Parameters:
  BitbucketUser:
    Type: String
    Description: The Bitbucket user name
  BitbucketPasswordParamStore:
    Type: String
    Description: Parameter store location of bitbucket password
  BitbucketRepoBranch:
    Type: String
    Default: master
    Description: The Git branch to be used
  Environment:
      Type: String
      Description: The build environment
  TerraformVersion:
    Type: String
    Default: 0.11.13
    Description: The Terraform version to use
  TerraformSha256:
    Type: String
    Default: 5925cd4d81e7d8f42a0054df2aafd66e2ab7408dbed2bd748f0022cfe592f8d2
    Description: HASHICORP - Y U NO PACKAGE REPOSITORY
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Source Code Repository
        Parameters:
          - BitbucketUser
          - BitbucketPassword
          - BitbucketRepoName
          - BitbucketRepoBranch
      - Label:
          default: Terraform
        Parameters:
          - TerraformVersion
          - TerraformSha256
      - Label:
          default: Environment
        Parameters:
          - Environment
Resources:
  TerraformStateBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      Tags:
        -
          Key: "env"
          Value: !Ref Environment

  InvokeTerraformBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  InvokeTerraformBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/eb-go-1.5-amazonlinux-64:2.1.3
        Type: LINUX_CONTAINER
      Tags:
        -
          Key: "env"
          Value: !Ref Environment
      Name: !Sub ${AWS::StackName}-TerraformApplyStep
      ServiceRole: !Ref InvokeTerraformBuildRole
      Source:
        Type: NO_SOURCE
        BuildSpec: !Sub |
          version: 0.1
          env:
            parameter-store:
              Env_BitbucketPassword: ${BitbucketPasswordParamStore}
          phases:
            install:
              commands:
                - cd /tmp && curl -o terraform.zip https://releases.hashicorp.com/terraform/${TerraformVersion}/terraform_${TerraformVersion}_linux_amd64.zip && echo "${TerraformSha256} terraform.zip" | sha256sum -c --quiet && unzip terraform.zip && mv terraform /usr/bin
            build:
              commands:
                - git clone -b ${BitbucketRepoBranch} https://${BitbucketUser}:$Env_BitbucketPassword@bitbucket.org/qriousnz/qv-terraform.git
                - cd qv-terraform && terraform init -backend-config="bucket=${TerraformStateBucket}" -backend-config="key=terraform/terraform.tfstate" -backend-config="region=ap-southeast-2"
                - cd qv-terraform && terraform apply -auto-approve -var-file="${Environment}.tfvars"
